include: package:flutter_lints/flutter.yaml

# Specify analysis options.

# Require trailing commas
# See: https://dart-lang.github.io/linter/lints/always_put_control_body_on_new_line.html
always_put_control_body_on_new_line: true
